### ISSUE TITLE
pod:      Unable to find a specification for `MCScratchImageView`

### ISSUE THREAD

**Issue by TML007** [Minecodecraft/MCScratchImageView#1]
Unable to find a specification for `MCScratchImageView`

**Comment by Minecodecraft** [comment]
Try to clean the Pod file & setup again

**Comment by Minecodecraft** [comment]
Try to clean the Pod file & setup again

**Comment by JaylenCoding** [comment]
Try to clean the Pod file and setup again in your project directory.

```Ruby
$ pod repo remove master
$ pod setup
```
